apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mykubernetes-79dd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mykubernetes-79dd"
  template:
    metadata:
      labels:
        app: "mykubernetes-79dd"
    spec:
      containers:
        - name: "mykubernetes-79dd"
          image: "harimcontainer.azurecr.io/mykubernetes"
          ports:
          - containerPort: 8080