on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: harimcontainer.azurecr.io
        username: ${{ secrets.acr_harimcontainer_username }}
        password: ${{ secrets.acr_harimcontainer_password }}
    
    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Gradle
      run: gradle build
      
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t harimcontainer.azurecr.io/mykubernetes:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push harimcontainer.azurecr.io/mykubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mykubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mykubernetes8957 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mykubernetes8957`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mykubernetes8957
        container-registry-url: harimcontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_harimcontainer_username }}
        container-registry-password: ${{ secrets.acr_harimcontainer_password }}
        secret-name: mykubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mykubernetes8957
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          harimcontainer.azurecr.io/mykubernetes:${{ github.sha }}
        imagepullsecrets: |
          mykubernetesdockerauth
